#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB_LINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BorgesBadevaerelser")]
	public partial class BB_LINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKunde(Kunde instance);
    partial void UpdateKunde(Kunde instance);
    partial void DeleteKunde(Kunde instance);
    partial void InsertRammeAftale(RammeAftale instance);
    partial void UpdateRammeAftale(RammeAftale instance);
    partial void DeleteRammeAftale(RammeAftale instance);
    partial void InsertNotat(Notat instance);
    partial void UpdateNotat(Notat instance);
    partial void DeleteNotat(Notat instance);
    partial void InsertPostBy(PostBy instance);
    partial void UpdatePostBy(PostBy instance);
    partial void DeletePostBy(PostBy instance);
    partial void InsertRabat(Rabat instance);
    partial void UpdateRabat(Rabat instance);
    partial void DeleteRabat(Rabat instance);
    #endregion
		
		public BB_LINQDataContext() : 
				base(global::BB_LINQ.Properties.Settings.Default.BorgesBadevaerelserConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BB_LINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BB_LINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BB_LINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BB_LINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Kunde> Kundes
		{
			get
			{
				return this.GetTable<Kunde>();
			}
		}
		
		public System.Data.Linq.Table<RammeAftale> RammeAftales
		{
			get
			{
				return this.GetTable<RammeAftale>();
			}
		}
		
		public System.Data.Linq.Table<Notat> Notats
		{
			get
			{
				return this.GetTable<Notat>();
			}
		}
		
		public System.Data.Linq.Table<PostBy> PostBies
		{
			get
			{
				return this.GetTable<PostBy>();
			}
		}
		
		public System.Data.Linq.Table<Rabat> Rabats
		{
			get
			{
				return this.GetTable<Rabat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kunde")]
	public partial class Kunde : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KundeID;
		
		private string _Kundenavn;
		
		private string _CVR;
		
		private string _Kundeadresse;
		
		private int _Postnummer;
		
		private EntitySet<RammeAftale> _RammeAftales;
		
		private EntityRef<PostBy> _PostBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKundeIDChanging(int value);
    partial void OnKundeIDChanged();
    partial void OnKundenavnChanging(string value);
    partial void OnKundenavnChanged();
    partial void OnCVRChanging(string value);
    partial void OnCVRChanged();
    partial void OnKundeadresseChanging(string value);
    partial void OnKundeadresseChanged();
    partial void OnPostnummerChanging(int value);
    partial void OnPostnummerChanged();
    #endregion
		
		public Kunde()
		{
			this._RammeAftales = new EntitySet<RammeAftale>(new Action<RammeAftale>(this.attach_RammeAftales), new Action<RammeAftale>(this.detach_RammeAftales));
			this._PostBy = default(EntityRef<PostBy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KundeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KundeID
		{
			get
			{
				return this._KundeID;
			}
			set
			{
				if ((this._KundeID != value))
				{
					this.OnKundeIDChanging(value);
					this.SendPropertyChanging();
					this._KundeID = value;
					this.SendPropertyChanged("KundeID");
					this.OnKundeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kundenavn", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Kundenavn
		{
			get
			{
				return this._Kundenavn;
			}
			set
			{
				if ((this._Kundenavn != value))
				{
					this.OnKundenavnChanging(value);
					this.SendPropertyChanging();
					this._Kundenavn = value;
					this.SendPropertyChanged("Kundenavn");
					this.OnKundenavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVR", DbType="NChar(8) NOT NULL", CanBeNull=false)]
		public string CVR
		{
			get
			{
				return this._CVR;
			}
			set
			{
				if ((this._CVR != value))
				{
					this.OnCVRChanging(value);
					this.SendPropertyChanging();
					this._CVR = value;
					this.SendPropertyChanged("CVR");
					this.OnCVRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kundeadresse", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Kundeadresse
		{
			get
			{
				return this._Kundeadresse;
			}
			set
			{
				if ((this._Kundeadresse != value))
				{
					this.OnKundeadresseChanging(value);
					this.SendPropertyChanging();
					this._Kundeadresse = value;
					this.SendPropertyChanged("Kundeadresse");
					this.OnKundeadresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postnummer", DbType="Int NOT NULL")]
		public int Postnummer
		{
			get
			{
				return this._Postnummer;
			}
			set
			{
				if ((this._Postnummer != value))
				{
					if (this._PostBy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPostnummerChanging(value);
					this.SendPropertyChanging();
					this._Postnummer = value;
					this.SendPropertyChanged("Postnummer");
					this.OnPostnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kunde_RammeAftale", Storage="_RammeAftales", ThisKey="KundeID", OtherKey="KundeID")]
		public EntitySet<RammeAftale> RammeAftales
		{
			get
			{
				return this._RammeAftales;
			}
			set
			{
				this._RammeAftales.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PostBy_Kunde", Storage="_PostBy", ThisKey="Postnummer", OtherKey="Postnr", IsForeignKey=true)]
		public PostBy PostBy
		{
			get
			{
				return this._PostBy.Entity;
			}
			set
			{
				PostBy previousValue = this._PostBy.Entity;
				if (((previousValue != value) 
							|| (this._PostBy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PostBy.Entity = null;
						previousValue.Kundes.Remove(this);
					}
					this._PostBy.Entity = value;
					if ((value != null))
					{
						value.Kundes.Add(this);
						this._Postnummer = value.Postnr;
					}
					else
					{
						this._Postnummer = default(int);
					}
					this.SendPropertyChanged("PostBy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RammeAftales(RammeAftale entity)
		{
			this.SendPropertyChanging();
			entity.Kunde = this;
		}
		
		private void detach_RammeAftales(RammeAftale entity)
		{
			this.SendPropertyChanging();
			entity.Kunde = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RammeAftale")]
	public partial class RammeAftale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AftaleID;
		
		private System.DateTime _Dato;
		
		private int _KundeID;
		
		private decimal _Rammebeloeb;
		
		private int _RabatID;
		
		private string _Kontaktperson;
		
		private EntitySet<Notat> _Notats;
		
		private EntityRef<Kunde> _Kunde;
		
		private EntityRef<Rabat> _Rabat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAftaleIDChanging(int value);
    partial void OnAftaleIDChanged();
    partial void OnDatoChanging(System.DateTime value);
    partial void OnDatoChanged();
    partial void OnKundeIDChanging(int value);
    partial void OnKundeIDChanged();
    partial void OnRammebeloebChanging(decimal value);
    partial void OnRammebeloebChanged();
    partial void OnRabatIDChanging(int value);
    partial void OnRabatIDChanged();
    partial void OnKontaktpersonChanging(string value);
    partial void OnKontaktpersonChanged();
    #endregion
		
		public RammeAftale()
		{
			this._Notats = new EntitySet<Notat>(new Action<Notat>(this.attach_Notats), new Action<Notat>(this.detach_Notats));
			this._Kunde = default(EntityRef<Kunde>);
			this._Rabat = default(EntityRef<Rabat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AftaleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AftaleID
		{
			get
			{
				return this._AftaleID;
			}
			set
			{
				if ((this._AftaleID != value))
				{
					this.OnAftaleIDChanging(value);
					this.SendPropertyChanging();
					this._AftaleID = value;
					this.SendPropertyChanged("AftaleID");
					this.OnAftaleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dato", DbType="Date NOT NULL")]
		public System.DateTime Dato
		{
			get
			{
				return this._Dato;
			}
			set
			{
				if ((this._Dato != value))
				{
					this.OnDatoChanging(value);
					this.SendPropertyChanging();
					this._Dato = value;
					this.SendPropertyChanged("Dato");
					this.OnDatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KundeID", DbType="Int NOT NULL")]
		public int KundeID
		{
			get
			{
				return this._KundeID;
			}
			set
			{
				if ((this._KundeID != value))
				{
					if (this._Kunde.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKundeIDChanging(value);
					this.SendPropertyChanging();
					this._KundeID = value;
					this.SendPropertyChanged("KundeID");
					this.OnKundeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rammebeloeb", DbType="Decimal(10,2) NOT NULL")]
		public decimal Rammebeloeb
		{
			get
			{
				return this._Rammebeloeb;
			}
			set
			{
				if ((this._Rammebeloeb != value))
				{
					this.OnRammebeloebChanging(value);
					this.SendPropertyChanging();
					this._Rammebeloeb = value;
					this.SendPropertyChanged("Rammebeloeb");
					this.OnRammebeloebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RabatID", DbType="Int NOT NULL")]
		public int RabatID
		{
			get
			{
				return this._RabatID;
			}
			set
			{
				if ((this._RabatID != value))
				{
					if (this._Rabat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRabatIDChanging(value);
					this.SendPropertyChanging();
					this._RabatID = value;
					this.SendPropertyChanged("RabatID");
					this.OnRabatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kontaktperson", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Kontaktperson
		{
			get
			{
				return this._Kontaktperson;
			}
			set
			{
				if ((this._Kontaktperson != value))
				{
					this.OnKontaktpersonChanging(value);
					this.SendPropertyChanging();
					this._Kontaktperson = value;
					this.SendPropertyChanged("Kontaktperson");
					this.OnKontaktpersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RammeAftale_Notat", Storage="_Notats", ThisKey="AftaleID", OtherKey="AftaleID")]
		public EntitySet<Notat> Notats
		{
			get
			{
				return this._Notats;
			}
			set
			{
				this._Notats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kunde_RammeAftale", Storage="_Kunde", ThisKey="KundeID", OtherKey="KundeID", IsForeignKey=true)]
		public Kunde Kunde
		{
			get
			{
				return this._Kunde.Entity;
			}
			set
			{
				Kunde previousValue = this._Kunde.Entity;
				if (((previousValue != value) 
							|| (this._Kunde.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kunde.Entity = null;
						previousValue.RammeAftales.Remove(this);
					}
					this._Kunde.Entity = value;
					if ((value != null))
					{
						value.RammeAftales.Add(this);
						this._KundeID = value.KundeID;
					}
					else
					{
						this._KundeID = default(int);
					}
					this.SendPropertyChanged("Kunde");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rabat_RammeAftale", Storage="_Rabat", ThisKey="RabatID", OtherKey="RabatID", IsForeignKey=true)]
		public Rabat Rabat
		{
			get
			{
				return this._Rabat.Entity;
			}
			set
			{
				Rabat previousValue = this._Rabat.Entity;
				if (((previousValue != value) 
							|| (this._Rabat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rabat.Entity = null;
						previousValue.RammeAftales.Remove(this);
					}
					this._Rabat.Entity = value;
					if ((value != null))
					{
						value.RammeAftales.Add(this);
						this._RabatID = value.RabatID;
					}
					else
					{
						this._RabatID = default(int);
					}
					this.SendPropertyChanged("Rabat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Notats(Notat entity)
		{
			this.SendPropertyChanging();
			entity.RammeAftale = this;
		}
		
		private void detach_Notats(Notat entity)
		{
			this.SendPropertyChanging();
			entity.RammeAftale = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Notat")]
	public partial class Notat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NotatID;
		
		private string _Notat1;
		
		private int _AftaleID;
		
		private System.DateTime _Opfoelgningsdato;
		
		private EntityRef<RammeAftale> _RammeAftale;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNotatIDChanging(int value);
    partial void OnNotatIDChanged();
    partial void OnNotat1Changing(string value);
    partial void OnNotat1Changed();
    partial void OnAftaleIDChanging(int value);
    partial void OnAftaleIDChanged();
    partial void OnOpfoelgningsdatoChanging(System.DateTime value);
    partial void OnOpfoelgningsdatoChanged();
    #endregion
		
		public Notat()
		{
			this._RammeAftale = default(EntityRef<RammeAftale>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotatID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NotatID
		{
			get
			{
				return this._NotatID;
			}
			set
			{
				if ((this._NotatID != value))
				{
					this.OnNotatIDChanging(value);
					this.SendPropertyChanging();
					this._NotatID = value;
					this.SendPropertyChanged("NotatID");
					this.OnNotatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Notat", Storage="_Notat1", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Notat1
		{
			get
			{
				return this._Notat1;
			}
			set
			{
				if ((this._Notat1 != value))
				{
					this.OnNotat1Changing(value);
					this.SendPropertyChanging();
					this._Notat1 = value;
					this.SendPropertyChanged("Notat1");
					this.OnNotat1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AftaleID", DbType="Int NOT NULL")]
		public int AftaleID
		{
			get
			{
				return this._AftaleID;
			}
			set
			{
				if ((this._AftaleID != value))
				{
					if (this._RammeAftale.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAftaleIDChanging(value);
					this.SendPropertyChanging();
					this._AftaleID = value;
					this.SendPropertyChanged("AftaleID");
					this.OnAftaleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opfoelgningsdato", DbType="Date NOT NULL")]
		public System.DateTime Opfoelgningsdato
		{
			get
			{
				return this._Opfoelgningsdato;
			}
			set
			{
				if ((this._Opfoelgningsdato != value))
				{
					this.OnOpfoelgningsdatoChanging(value);
					this.SendPropertyChanging();
					this._Opfoelgningsdato = value;
					this.SendPropertyChanged("Opfoelgningsdato");
					this.OnOpfoelgningsdatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RammeAftale_Notat", Storage="_RammeAftale", ThisKey="AftaleID", OtherKey="AftaleID", IsForeignKey=true)]
		public RammeAftale RammeAftale
		{
			get
			{
				return this._RammeAftale.Entity;
			}
			set
			{
				RammeAftale previousValue = this._RammeAftale.Entity;
				if (((previousValue != value) 
							|| (this._RammeAftale.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RammeAftale.Entity = null;
						previousValue.Notats.Remove(this);
					}
					this._RammeAftale.Entity = value;
					if ((value != null))
					{
						value.Notats.Add(this);
						this._AftaleID = value.AftaleID;
					}
					else
					{
						this._AftaleID = default(int);
					}
					this.SendPropertyChanged("RammeAftale");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PostBy")]
	public partial class PostBy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Postnr;
		
		private string _Bynavn;
		
		private EntitySet<Kunde> _Kundes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPostnrChanging(int value);
    partial void OnPostnrChanged();
    partial void OnBynavnChanging(string value);
    partial void OnBynavnChanged();
    #endregion
		
		public PostBy()
		{
			this._Kundes = new EntitySet<Kunde>(new Action<Kunde>(this.attach_Kundes), new Action<Kunde>(this.detach_Kundes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postnr", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Postnr
		{
			get
			{
				return this._Postnr;
			}
			set
			{
				if ((this._Postnr != value))
				{
					this.OnPostnrChanging(value);
					this.SendPropertyChanging();
					this._Postnr = value;
					this.SendPropertyChanged("Postnr");
					this.OnPostnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bynavn", DbType="VarChar(25)")]
		public string Bynavn
		{
			get
			{
				return this._Bynavn;
			}
			set
			{
				if ((this._Bynavn != value))
				{
					this.OnBynavnChanging(value);
					this.SendPropertyChanging();
					this._Bynavn = value;
					this.SendPropertyChanged("Bynavn");
					this.OnBynavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PostBy_Kunde", Storage="_Kundes", ThisKey="Postnr", OtherKey="Postnummer")]
		public EntitySet<Kunde> Kundes
		{
			get
			{
				return this._Kundes;
			}
			set
			{
				this._Kundes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Kundes(Kunde entity)
		{
			this.SendPropertyChanging();
			entity.PostBy = this;
		}
		
		private void detach_Kundes(Kunde entity)
		{
			this.SendPropertyChanging();
			entity.PostBy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rabat")]
	public partial class Rabat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RabatID;
		
		private decimal _Rabatprocent;
		
		private EntitySet<RammeAftale> _RammeAftales;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRabatIDChanging(int value);
    partial void OnRabatIDChanged();
    partial void OnRabatprocentChanging(decimal value);
    partial void OnRabatprocentChanged();
    #endregion
		
		public Rabat()
		{
			this._RammeAftales = new EntitySet<RammeAftale>(new Action<RammeAftale>(this.attach_RammeAftales), new Action<RammeAftale>(this.detach_RammeAftales));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RabatID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RabatID
		{
			get
			{
				return this._RabatID;
			}
			set
			{
				if ((this._RabatID != value))
				{
					this.OnRabatIDChanging(value);
					this.SendPropertyChanging();
					this._RabatID = value;
					this.SendPropertyChanged("RabatID");
					this.OnRabatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rabatprocent", DbType="Decimal(3,2) NOT NULL")]
		public decimal Rabatprocent
		{
			get
			{
				return this._Rabatprocent;
			}
			set
			{
				if ((this._Rabatprocent != value))
				{
					this.OnRabatprocentChanging(value);
					this.SendPropertyChanging();
					this._Rabatprocent = value;
					this.SendPropertyChanged("Rabatprocent");
					this.OnRabatprocentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rabat_RammeAftale", Storage="_RammeAftales", ThisKey="RabatID", OtherKey="RabatID")]
		public EntitySet<RammeAftale> RammeAftales
		{
			get
			{
				return this._RammeAftales;
			}
			set
			{
				this._RammeAftales.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RammeAftales(RammeAftale entity)
		{
			this.SendPropertyChanging();
			entity.Rabat = this;
		}
		
		private void detach_RammeAftales(RammeAftale entity)
		{
			this.SendPropertyChanging();
			entity.Rabat = null;
		}
	}
}
#pragma warning restore 1591
