//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;

namespace BB_LINQ {
    public class RammeAftaleViewModel {
        private RammeAftale _rammeaftale;

        private Kunde _kunde;

        private Rabat _rabat;

        private PostBy _postby;

        private List<Notat> _notater;

        private int _notatnr = 1;

        public RammeAftaleViewModel() {

        }

        public RammeAftaleViewModel(int nr) {
            BB_LINQDataContext db = new BB_LINQDataContext(DB.connectionString);
            try {
                _rammeaftale = db.RammeAftales.OrderBy(x => x.AftaleID).Skip(nr - 1).Take(1).ToArray()[0];
                _kunde = db.Kundes.Where(x => x.KundeID == _rammeaftale.KundeID).First();
                _rabat = db.Rabats.Where(x => x.RabatID == _rammeaftale.RabatID).First();
                _postby = db.PostBies.Where(x => x.Postnr == _kunde.Postnummer).First();
                _notater = db.Notats.Where(x => x.AftaleID == _rammeaftale.AftaleID).ToList();
            } catch (Exception ex) {
                Debug.WriteLine(ex.Message);
            }

        }

        public string Kundenavn
        {
            get { return _kunde.Kundenavn; }
            set { _kunde.Kundenavn = value; }
        }

        public string CVR
        {
            get { return _kunde.CVR; }
            set { _kunde.CVR = value; }
        }

        public string Kundeadresse
        {
            get { return _kunde.Kundeadresse; }
            set { _kunde.Kundeadresse = value; }
        }

        public string Postnummer
        {
            get { return _postby.Postnr.ToString(); }
            set { _postby.Postnr = int.Parse(value); }
        }

        public string Bynavn
        {
            get { return _postby.Bynavn; }
            set { _postby.Bynavn = value; }
        }

        public decimal RabatProcent
        {
            get { return _rabat.Rabatprocent; }
            set { _rabat.Rabatprocent = value; }
        }

        public decimal Rammebeloeb
        {
            get { return _rammeaftale.Rammebeloeb; }
            set { _rammeaftale.Rammebeloeb = value; }
        }

        public string Kontaktperson
        {
            get { return _rammeaftale.Kontaktperson; }
            set { _rammeaftale.Kontaktperson = value; }
        }



        public string Notat
        {
            get { return _notater[_notatnr].Notat1; }
            set { _notater[_notatnr].Notat1 = value; }
        }

    }


}
