//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class RammeAftaleViewModel
{
	private RammeAftale _rammeaftale
	{
		get;
		set;
	}

	private Kunde _kunde
	{
		get;
		set;
	}

	private Rabat _rabat
	{
		get;
		set;
	}

	private PostBy _postby
	{
		get;
		set;
	}

	private List<Notat> _notater
	{
		get;
		set;
	}

	public virtual string Kundenavn
	{
		get;
		set;
	}

	public virtual string CVR
	{
		get;
		set;
	}

	public virtual string Kundeadresse
	{
		get;
		set;
	}

	public virtual string Postnummer
	{
		get;
		set;
	}

	public virtual string Bynavn
	{
		get;
		set;
	}

	public virtual decimal RabatProcent
	{
		get;
		set;
	}

	public virtual decimal Rammebeloeb
	{
		get;
		set;
	}

	public virtual string Kontaktperson
	{
		get;
		set;
	}

	private int _notatnr
	{
		get;
		set;
	}

	public virtual string Notat
	{
		get;
		set;
	}

}

